### ISSUE TITLE
Only compatible with python 2.7 and PyPy

### ISSUE THREAD

**Issue by kindjar** [delighted/delighted-python#1]
CI is set up to also test 2.6, 3.2, 3.3.3.4, and pypy3, but none of those work. 2.6 fails because of changes to the parameter list of assertRaises, and all the 3 versions fails because urlparse got rearranged in the standard library for 3....

**Comment by mkdynamic** [comment]
@kindjar Did this get fixed on master in the recent activity?

**Comment by kindjar** [comment]
Yes, it did, the test suite now passes in python 2.6 - 3.4.
