### ISSUE TITLE
'Person' Resource should be an AllResource as well as CreatableResource

### ISSUE THREAD

**Issue by sadjar87** [delighted/delighted-python#13]
Simple solution is:
```
class Person(AllResource, CreateableResource):
    path = 'people'
```
to hit `/v1/people.json` endpoint.

**Comment by mkdynamic** [comment]
@kindjar Would you mind to take this?

**Comment by kindjar** [comment]
@sadjar87 Please check out version 2.2.0rc1 of this library and see if it works for you now. Thanks!

**Comment by sadjar87** [comment]
Works, cheers.
