### ISSUE TITLE
Automatic backoff on TooManyRequests error

### ISSUE THREAD

**Issue by Hello1024** [delighted/delighted-python#16]
Rather than the user having to handle the too many requests error, I would like to see it (optionally) handled internally within the library by simply implementing an internal synchronous sleep followed by a retry.

Might be as simple as having a shim with this decorator:
https://www.saltycrane.com/blog/2009/11/trying-out-retry-decorator-python/

User code gets very messy otherwise.

**Comment by mkdynamic** [comment]
@Hello1024 Thanks for the suggestion, I can def. see that built in support for this simplify things in this case. However, this is not something we currently plan to implement. We don't believe that it's possible to handle retries and backoff in a way that would work broadly and generally (for different frameworks, job queues, libraries, concurrency models etc.).
