### ISSUE TITLE
Get all responses

### ISSUE THREAD

**Issue by bronsonelliott** [delighted/delighted-python#17]
I'm trying to write the proper code to retrieve **all** responses from a survey.  I see the 'per_page' setting and  the max value is 100.  The only way I've been able to figure out how to get all responses is the create a loop and try to guess how many pages there are.

`for x in range(1, 100):
    df = pd.DataFrame(delighted.SurveyResponse.all(page=x, per_page=100))
    result = pd.concat([result, df])`

Is there a way to get all responses another way?

**Comment by mkdynamic** [comment]
@bronsonelliott The recommended way is to keep looping until you get no results, something like this:

```python
x = 0
while True:
    df = pd.DataFrame(delighted.SurveyResponse.all(page = x, per_page = 100))
    result = pd.concat([result, df])
    if df.count == 0:
      break # We are past the last page, no more results
    x += 1
```

Let me know if that works.

**Comment by bronsonelliott** [comment]
Worked great. Thank you for your help.
