### ISSUE TITLE
Not using client's api_key

### ISSUE THREAD

**Issue by banga** [delighted/delighted-python#7]
On https://github.com/delighted/delighted-python/blob/master/delighted/client.py#L34 shouldn't it be `self.api_key`?

**Comment by mkdynamic** [comment]
Yes! Good catch. I think we'll need to set the default value of `self.api_key` in the constructor to `delighted.api_key` too.

**Comment by banga** [comment]
also `self.api_base_url` on line 39

**Comment by mkdynamic** [comment]
Ah yep, thanks. We'll get this fixed.

**Comment by mkdynamic** [comment]
This now is fixed and released in 1.1.2. Let us know how it goes.
